#!/bin/bash

sxhkd -m -1 &

bspc config border_width                      0
bspc config window_gap                        20
bspc config top_padding                       30
bspc config bottom_padding                    30
bspc config left_padding                      0
bspc config right_padding                     0

bspc config remove_disabled_monitors          true
bspc config remove_unplugged_monitors         true

bspc config split_ratio                       0.52
bspc config borderless_monocle                true
bspc config gapless_monocle                   true
bspc config focus_follows_pointer             true

bspc config pointer_modifier                  mod4
bspc config pointer_action1                   move
bspc config pointer_action2                   resize_side
bspc config pointer_action3                   resize_corner

bspc rule -a Zoiper state=tiled
bspc rule -a Tilda state=floating focus layer=ABOVE 
bspc rule -a Guake state=floating locked=on desktop=focused 
bspc rule -a jetbrains-studio state=floating
bspc rule -a java-lang-Thread state=floating

wm.displays

~/.config/bspwm/autostart

